Repository unnoq/orpc, pull requests merged in 2025-08, with the labels that each got.

#814 fix(openapi): support strict object schema for dynamic params
  packages/openapi/src/schema-utils.test.ts
  packages/openapi/src/schema-utils.ts
Labels: size:M

#828 docs: typo
  apps/content/docs/middleware.md
Labels: size:XS

#840 fix(tanstack-query): default enabled option not working
  packages/react-query/src/procedure-utils.test.ts
  packages/react-query/src/procedure-utils.ts
  packages/react-query/src/types.ts
  packages/solid-query/src/procedure-utils.test.ts
  packages/solid-query/src/procedure-utils.ts
  packages/solid-query/src/types.ts
  packages/svelte-query/src/procedure-utils.test.tsx
  packages/svelte-query/src/procedure-utils.ts
  packages/svelte-query/src/types.ts
  packages/tanstack-query/src/procedure-utils.test-d.ts
  packages/tanstack-query/src/procedure-utils.test.ts
  packages/tanstack-query/src/procedure-utils.ts
  packages/tanstack-query/src/types.ts
  packages/vue-query/src/procedure-utils.test.ts
  packages/vue-query/src/procedure-utils.ts
  packages/vue-query/src/types.ts
Labels: size:M

#847 docs: SEO improvements
  apps/content/.vitepress/config.ts
  apps/content/public/robots.txt
Labels: size:XS, lgtm

#854 feat(server): stable hibernation apis
  apps/content/docs/plugins/hibernation.md
  packages/durable-event-iterator/src/durable-object/handler.test.ts
  packages/durable-event-iterator/src/durable-object/handler.ts
  packages/durable-event-iterator/src/durable-object/object.ts
  packages/durable-event-iterator/src/durable-object/websocket-manager.test.ts
  packages/durable-event-iterator/src/durable-object/websocket-manager.ts
  packages/server/src/hibernation/event-iterator.test.ts
  packages/server/src/hibernation/event-iterator.ts
  packages/server/src/hibernation/index.ts
  packages/server/src/hibernation/plugin.test.ts
  packages/server/src/hibernation/plugin.ts
  packages/server/src/procedure-client.ts
  packages/standard-server-peer/src/server.test.ts
  packages/standard-server-peer/src/server.ts
  packages/standard-server/src/hibernation.test.ts
  packages/standard-server/src/hibernation.ts
Labels: size:M

#862 docs: Update TanStack Query Integration docs to handle query key serialization of RPC data types
  apps/content/docs/integrations/tanstack-query.md
Labels: size:XS, lgtm

#869 feat(server): Compression Plugin
  .github/dependabot.yml
  apps/content/.vitepress/config.ts
  apps/content/docs/plugins/body-limit.md
  apps/content/docs/plugins/compression.md
  packages/server/build.config.ts
  packages/server/package.json
  packages/server/src/adapters/fetch/compression-plugin.test.ts
  packages/server/src/adapters/fetch/compression-plugin.ts
  packages/server/src/adapters/fetch/index.ts
  packages/server/src/adapters/node/compression-plugin.test.ts
  packages/server/src/adapters/node/compression-plugin.ts
  packages/server/src/adapters/node/index.ts
  pnpm-lock.yaml
Labels: size:XL

#873 refactor: introduce @orpc/interop package for compatibility layer
  .github/dependabot.yml
  eslint.config.js
  packages/interop/.gitignore
  packages/interop/README.md
  packages/interop/build.config.ts
  packages/interop/package.json
  packages/interop/src/compression/index.test.ts
  packages/interop/src/compression/index.ts
  packages/interop/src/json-schema-typed/draft-07.test.ts
  packages/interop/src/json-schema-typed/draft-07.ts
  packages/interop/src/json-schema-typed/draft-2019-09.test.ts
  packages/interop/src/json-schema-typed/draft-2019-09.ts
  packages/interop/src/json-schema-typed/draft-2020-12.test.ts
  packages/interop/src/json-schema-typed/draft-2020-12.ts
  packages/interop/src/json-schema-typed/index.test.ts
  packages/interop/src/json-schema-typed/index.ts
  packages/interop/tsconfig.json
  packages/json-schema-typed/package.json
  packages/json-schema/package.json
  packages/json-schema/src/types.ts
  packages/json-schema/tsconfig.json
  packages/openapi/package.json
  packages/openapi/src/schema.ts
  packages/openapi/tsconfig.json
  packages/otel/src/instrumentation.ts
  packages/server/build.config.ts
  packages/server/package.json
  packages/server/src/adapters/node/compression-plugin.ts
  packages/server/tsconfig.json
  pnpm-lock.yaml
Labels: size:L

#878 fix(tanstack-query): exactOptionalPropertyTypes
  packages/react-query/src/procedure-utils.test.ts
  packages/react-query/src/procedure-utils.ts
  packages/react-query/src/types.ts
  packages/solid-query/src/procedure-utils.test.ts
  packages/solid-query/src/procedure-utils.ts
  packages/solid-query/src/types.ts
  packages/svelte-query/src/procedure-utils.test.tsx
  packages/svelte-query/src/procedure-utils.ts
  packages/svelte-query/src/types.ts
  packages/tanstack-query/src/procedure-utils.test-d.ts
  packages/tanstack-query/src/procedure-utils.test.ts
  packages/tanstack-query/src/procedure-utils.ts
  packages/tanstack-query/src/types.ts
Labels: size:M

#880 feat(server): compression plugin filter option should override default content type filter
  packages/server/src/adapters/fetch/compression-plugin.test.ts
  packages/server/src/adapters/fetch/compression-plugin.ts
  packages/server/src/adapters/node/compression-plugin.test.ts
  packages/server/src/adapters/node/compression-plugin.ts
Labels: size:L

#883 docs: Publish Client to NPM
  apps/content/.vitepress/config.ts
  apps/content/docs/advanced/publish-client-to-npm.md
Labels: size:L

#887 fix(client): prevent unintended procedure calls when awaiting client
  packages/client/src/client.test.ts
  packages/client/src/client.ts
  packages/shared/src/index.ts
  packages/shared/src/proxy.test.ts
  packages/shared/src/proxy.ts
Labels: size:L

#893 fix(server): apply error validation to event iterator
  packages/server/src/procedure-client.test.ts
  packages/server/src/procedure-client.ts
Labels: size:M

#916 feat(nest): add async configuration support for ORPCModule
  apps/content/docs/openapi/integrations/implement-contract-in-nest.md
  packages/nest/src/implement.test.ts
  packages/nest/src/module.ts
Labels: size:M

#923 refactor(shared): improve replicateAsyncIterator
  packages/shared/src/iterator.ts
Labels: size:M

#945 docs: Add oRPC Shield to ecosystem documentation
  apps/content/docs/ecosystem.md
Labels: size:S, lgtm

#946 feat(client): support fetch headers in link options
  apps/content/docs/adapters/next.md
  apps/content/docs/adapters/nuxt.md
  apps/content/docs/adapters/solid-start.md
  packages/client/src/adapters/standard/rpc-link-codec.test.ts
  packages/client/src/adapters/standard/rpc-link-codec.ts
  packages/client/src/adapters/standard/utils.test.ts
  packages/client/src/adapters/standard/utils.ts
  packages/openapi-client/src/adapters/standard/openapi-link-codec.test.ts
  packages/openapi-client/src/adapters/standard/openapi-link-codec.ts
  packages/standard-server-fetch/src/headers.ts
  playgrounds/solid-start/src/lib/orpc.ts
Labels: size:L

#949 feat(contract): add failed data to ValidationError for debugging
  packages/contract/src/error.ts
  packages/contract/src/event-iterator.test.ts
  packages/contract/src/event-iterator.ts
  packages/server/src/procedure-client.ts
Labels: size:S
