Repository unnoq/orpc, pull requests merged in 2025-07, with the labels that each got.

#710 feat(nest): module configuration
  apps/content/docs/openapi/integrations/implement-contract-in-nest.md
  packages/nest/build.config.ts
  packages/nest/src/implement.test.ts
  packages/nest/src/implement.ts
  packages/nest/src/index.ts
  packages/nest/src/module.ts
  packages/nest/tsconfig.json
  playgrounds/nest/build.config.ts
  playgrounds/nest/package.json
  playgrounds/nest/src/app.module.ts
  pnpm-lock.yaml
Labels: size:L

#716 feat(trpc): support event iterator for toORPCRouter
  packages/trpc/package.json
  packages/trpc/src/to-orpc-router.test-d.ts
  packages/trpc/src/to-orpc-router.test.ts
  packages/trpc/src/to-orpc-router.ts
  packages/trpc/tests/shared.ts
  packages/trpc/tsconfig.json
  pnpm-lock.yaml
Labels: size:L

#717 refactor: improve isAsyncIteratorObject util
  packages/shared/src/iterator.test.ts
  packages/shared/src/iterator.ts
Labels: size:XS

#726 docs: Customizing Error Response Format
  apps/content/.vitepress/config.ts
  apps/content/docs/openapi/advanced/customizing-error-response.md
  apps/content/docs/rpc-handler.md
Labels: size:M

#752 docs: improve "Router to Contract"
  apps/content/docs/contract-first/router-to-contract.md
Labels: size:XS, lgtm

#761 docs: typo
  apps/content/blog/v1-announcement.md
Labels: size:XS, lgtm

#762 feat(standard-server-aws-lambda): promote to stable
  apps/content/docs/adapters/http.md
  packages/openapi/src/adapters/aws-lambda/openapi-handler.test.ts
  packages/openapi/src/adapters/aws-lambda/openapi-handler.ts
  packages/server/src/adapters/aws-lambda/rpc-handler.test.ts
  packages/server/src/adapters/aws-lambda/rpc-handler.ts
Labels: size:S

#763 feat(zod): promote zod4 converter to stable
  README.md
  apps/content/docs/openapi/getting-started.md
  apps/content/docs/openapi/openapi-specification.md
  apps/content/docs/openapi/plugins/openapi-reference.md
  packages/json-schema/src/smart-coercion-plugin.test.ts
  packages/openapi/src/openapi-generator.test.ts
  packages/zod/README.md
  packages/zod/src/zod4/converter.components.test.ts
  packages/zod/src/zod4/converter.test.ts
  packages/zod/src/zod4/converter.ts
  packages/zod/tests/shared.ts
  playgrounds/astro/src/pages/api/[...rest].ts
  playgrounds/contract-first/src/main.ts
  playgrounds/nest/src/reference/reference.service.ts
  playgrounds/next/src/app/api/[[...rest]]/route.ts
  playgrounds/nuxt/server/routes/api/[...].ts
  playgrounds/solid-start/src/routes/api/[...rest].ts
  playgrounds/svelte-kit/src/routes/api/[...rest]/+server.ts
  playgrounds/tanstack-start/src/routes/api/$.ts
Labels: size:M

#766 feat(standard-server-peer): promote to stable
  apps/content/docs/adapters/browser.md
  apps/content/docs/adapters/electron.md
  apps/content/docs/adapters/message-port.md
  apps/content/docs/adapters/websocket.md
  apps/content/docs/adapters/worker-threads.md
  apps/content/docs/plugins/hibernation.md
  packages/arktype/README.md
  packages/client/src/adapters/message-port/link-client.ts
  packages/client/src/adapters/message-port/rpc-link.test.ts
  packages/client/src/adapters/message-port/rpc-link.ts
  packages/client/src/adapters/websocket/link-client.ts
  packages/client/src/adapters/websocket/rpc-link.test.ts
  packages/client/src/adapters/websocket/rpc-link.ts
  packages/durable-event-iterator/src/client/plugin.ts
  packages/durable-event-iterator/src/durable-object/object.ts
  packages/server/src/adapters/bun-ws/handler.ts
  packages/server/src/adapters/bun-ws/rpc-handler.test.ts
  packages/server/src/adapters/bun-ws/rpc-handler.ts
  packages/server/src/adapters/crossws/handler.ts
  packages/server/src/adapters/message-port/handler.ts
  packages/server/src/adapters/message-port/rpc-handler.test.ts
  packages/server/src/adapters/message-port/rpc-handler.ts
  packages/server/src/adapters/standard-peer/utils.test.ts
  packages/server/src/adapters/standard-peer/utils.ts
  packages/server/src/adapters/websocket/handler.ts
  packages/server/src/adapters/websocket/rpc-handler.test.ts
  packages/server/src/adapters/websocket/rpc-handler.ts
  packages/server/src/adapters/ws/handler.ts
  packages/server/src/adapters/ws/rpc-handler.test.ts
  packages/server/src/adapters/ws/rpc-handler.ts
  packages/server/tests/message-port.test.ts
  playgrounds/browser-extension/entrypoints/background/index.ts
  playgrounds/browser-extension/entrypoints/popup/lib/orpc.ts
  playgrounds/electron/src/main/index.ts
  playgrounds/electron/src/renderer/src/lib/orpc.ts
Labels: size:L

#758 feat(trpc): restructure ORPCMeta + accessible lazy router
  apps/content/docs/openapi/integrations/trpc.md
  packages/shared/src/object.ts
  packages/trpc/src/to-orpc-router.test.ts
  packages/trpc/src/to-orpc-router.ts
  packages/trpc/tests/shared.ts
Labels: size:M

#774 feat(zod): support zod meta `title` in generated JSON schema
  packages/zod/src/zod4/converter.meta.test.ts
  packages/zod/src/zod4/converter.ts
Labels: size:S, lgtm

#770 feat(server, openapi): add filter option to handlers
  apps/content/docs/openapi/openapi-handler.md
  apps/content/docs/openapi/openapi-specification.md
  apps/content/docs/rpc-handler.md
  packages/openapi/src/adapters/standard/openapi-handler.ts
  packages/openapi/src/adapters/standard/openapi-matcher.test.ts
  packages/openapi/src/adapters/standard/openapi-matcher.ts
  packages/openapi/src/openapi-generator.ts
  packages/server/src/adapters/standard/rpc-handler.ts
  packages/server/src/adapters/standard/rpc-matcher.test.ts
  packages/server/src/adapters/standard/rpc-matcher.ts
  packages/server/src/router-utils.ts
Labels: size:L

#775 feat: stream converter utils + AI SDK examples
  apps/content/.vitepress/config.ts
  apps/content/docs/integrations/ai-sdk.md
  apps/content/package.json
  packages/client/src/index.ts
  packages/server/src/index.ts
  packages/shared/src/index.ts
  packages/shared/src/stream.test.ts
  packages/shared/src/stream.ts
  pnpm-lock.yaml
Labels: size:L

#790 feat(zod): support zod v4 and v3 SchemaConverter use in parallel
  packages/zod/src/converter.test.ts
  packages/zod/src/converter.ts
  packages/zod/src/zod4/converter.test.ts
  packages/zod/src/zod4/converter.ts
Labels: size:S

#796 docs: Overview of Learn & Contribute
  apps/content/.vitepress/config.ts
  apps/content/learn-and-contribute/overview.md
Labels: size:M

#801 docs: mini orpc
  apps/content/.vitepress/config.ts
  apps/content/learn-and-contribute/mini-orpc/beyond-the-basics.md
  apps/content/learn-and-contribute/mini-orpc/client-side-client.md
  apps/content/learn-and-contribute/mini-orpc/overview.md
  apps/content/learn-and-contribute/mini-orpc/procedure-builder.md
  apps/content/learn-and-contribute/mini-orpc/server-side-client.md
  apps/content/package.json
  eslint.config.js
  pnpm-lock.yaml
Labels: size:XXL

#805 feat(server): helpers
  apps/content/.vitepress/config.ts
  apps/content/docs/helpers/base64url.md
  apps/content/docs/helpers/cookie.md
  apps/content/docs/helpers/encryption.md
  apps/content/docs/helpers/signing.md
  apps/content/docs/plugins/request-headers.md
  apps/content/docs/plugins/response-headers.md
  packages/server/package.json
  packages/server/src/helpers/base64url.test.ts
  packages/server/src/helpers/base64url.ts
  packages/server/src/helpers/cookie.test.ts
  packages/server/src/helpers/cookie.ts
  packages/server/src/helpers/encryption.test.ts
  packages/server/src/helpers/encryption.ts
  packages/server/src/helpers/index.ts
  packages/server/src/helpers/signing.test.ts
  packages/server/src/helpers/signing.ts
  pnpm-lock.yaml
Labels: size:XL

#811 fix(json-schema): enhance array to map coercion to handle unique keys
  apps/content/docs/openapi/plugins/smart-coercion.md
  packages/json-schema/src/coercer.test.ts
  packages/json-schema/src/coercer.ts
Labels: size:S
