Repository unnoq/orpc, pull requests merged in 2025-09, with the labels that each got.

#951 feat(openapi): form-data helpers
  apps/content/.vitepress/config.ts
  apps/content/docs/helpers/form-data.md
  apps/content/docs/openapi/bracket-notation.md
  apps/content/docs/server-action.md
  packages/openapi-client/package.json
  packages/openapi-client/src/helpers/index.test.ts
  packages/openapi-client/src/helpers/index.ts
Labels: size:L

#953 feat(contract): Response Validation Plugin
  apps/content/.vitepress/config.ts
  apps/content/docs/openapi/advanced/expanding-type-support-for-openapi-link.md
  apps/content/docs/openapi/client/openapi-link.md
  apps/content/docs/plugins/client-retry.md
  apps/content/docs/plugins/response-validation.md
  packages/contract/package.json
  packages/contract/src/error.test.ts
  packages/contract/src/error.ts
  packages/contract/src/plugins/index.test.ts
  packages/contract/src/plugins/index.ts
  packages/contract/src/plugins/response-validation.test.ts
  packages/contract/src/plugins/response-validation.ts
  packages/server/src/error.test.ts
  packages/server/src/error.ts
  packages/server/src/index.ts
  packages/server/src/procedure-client.test.ts
  packages/server/src/procedure-client.ts
Labels: size:XL

#970 feat(contract): improve `eventIterator` schema output type
  packages/contract/src/event-iterator.ts
Labels: size:XS

#968 refactor: migrate async generator to AsyncIteratorClass
  packages/client/src/plugins/retry.test.ts
  packages/client/src/plugins/retry.ts
  packages/server/src/plugins/batch.ts
  packages/standard-server/src/batch/response.test.ts
  packages/standard-server/src/batch/response.ts
Labels: size:L

#972 feat(client): support ORPCError instanceof checks across different dependency graph
  packages/client/build.config.ts
  packages/client/src/consts.ts
  packages/client/src/error.test.ts
  packages/client/src/error.ts
  packages/client/src/index.ts
  packages/shared/src/object.test.ts
  packages/shared/src/object.ts
Labels: size:L

#980 docs: video testimonials
  apps/content/.vitepress/theme/components/VideoTestimonials.vue
  apps/content/index.md
Labels: size:M

#982 docs: Monorepo Setup
  apps/content/.vitepress/config.ts
  apps/content/docs/best-practices/monorepo-setup.md
  eslint.config.js
Labels: size:M

#1000 feat(contract): Request Validation Plugin
  apps/content/.vitepress/config.ts
  apps/content/docs/plugins/request-validation.md
  packages/contract/src/plugins/index.ts
  packages/contract/src/plugins/request-validation.test.ts
  packages/contract/src/plugins/request-validation.ts
Labels: size:L

#1007 docs: prefer fetch adapter for nuxtjs
  apps/content/docs/adapters/nuxt.md
  playgrounds/nuxt/server/routes/api/[...].ts
  playgrounds/nuxt/server/routes/rpc/[...].ts
Labels: size:M

#1013 docs: web worker adapter
  apps/content/.vitepress/config.ts
  apps/content/docs/adapters/message-port.md
  apps/content/docs/adapters/web-workers.md
  apps/content/docs/adapters/worker-threads.md
  eslint.config.js
Labels: size:M, lgtm

#1028 docs: expo/fetch
  apps/content/docs/adapters/react-native.md
Labels: size:S

#1031 docs: Rename DurableEventIterator to DurableIterator
  apps/content/docs/integrations/durable-iterator.md
Labels: size:M, lgtm

#1037 docs: fix tanstack-start getRequestHeaders
  apps/content/docs/adapters/tanstack-start.md
Labels: size:XS, lgtm

#1032 feat(durable-iterator): x-orpc-durable-iterator header
  apps/content/docs/integrations/durable-iterator.md
  packages/durable-iterator/src/consts.ts
Labels: size:S

#1041 fix(standard-server): handle node:http malformed url
  packages/standard-server-node/src/url.test.ts
  packages/standard-server-node/src/url.ts
Labels: size:S

#1001 feat(standard-server): support parsed body in node adapter
  apps/content/docs/adapters/express.md
  apps/content/docs/adapters/next.md
  packages/nest/src/implement.ts
  packages/standard-server-node/src/body.test.ts
  packages/standard-server-node/src/body.ts
  packages/standard-server-node/src/types.ts
Labels: size:M, lgtm
