Repository unnoq/orpc, pull requests merged in 2025-06, with the labels that each got.

#638 feat(openapi): gen spec with common schemas - `components.schemas`
  apps/content/docs/openapi/openapi-specification.md
  packages/openapi/src/openapi-generator.test.ts
  packages/openapi/src/openapi-generator.ts
  packages/openapi/src/openapi-utils.test.ts
  packages/openapi/src/openapi-utils.ts
  packages/openapi/src/schema-converter.ts
  packages/zod/src/converter.components.test.ts
  packages/zod/src/converter.test.ts
  packages/zod/src/converter.ts
  packages/zod/src/zod4/converter.components.test.ts
  packages/zod/src/zod4/converter.test.ts
  packages/zod/src/zod4/converter.ts
  playgrounds/astro/src/pages/api/[...rest].ts
  playgrounds/contract-first/src/main.ts
  playgrounds/nest/src/reference/reference.service.ts
  playgrounds/next/src/app/api/[[...rest]]/route.ts
  playgrounds/nuxt/server/routes/api/[...].ts
  playgrounds/solid-start/src/routes/api/[...rest].ts
  playgrounds/svelte-kit/src/routes/api/[...rest]/+server.ts
  playgrounds/tanstack-start/src/routes/api/$.ts
Labels: size:XXL

#642 fix(openapi): OpenAPIGenerator make response headers optional when headers object is optional
  packages/openapi/src/openapi-generator.test.ts
  packages/openapi/src/openapi-generator.ts
Labels: size:S

#643 chore: improve stringifyJSON in case toJSON exists
  packages/shared/src/json.test-d.ts
  packages/shared/src/json.test.ts
  packages/shared/src/json.ts
Labels: size:XS

#650 docs: deal with body already used error in "Elysia Adapter"
  apps/content/docs/adapters/elysia.md
Labels: size:XS

#672 feat(zod): place null at the end when converting ZodNullable
  packages/zod/src/converter.test.ts
  packages/zod/src/converter.ts
Labels: size:XS, lgtm

#668 feat(durable-event-iterator): implement event iterator with Cloudflare hibernation and more
  apps/content/.vitepress/config.ts
  apps/content/docs/integrations/durable-event-iterator.md
  package.json
  packages/durable-event-iterator/.gitignore
  packages/durable-event-iterator/README.md
  packages/durable-event-iterator/build.config.ts
  packages/durable-event-iterator/package.json
  packages/durable-event-iterator/src/client/contract.ts
  packages/durable-event-iterator/src/client/event-iterator.test-d.ts
  packages/durable-event-iterator/src/client/event-iterator.test.ts
  packages/durable-event-iterator/src/client/event-iterator.ts
  packages/durable-event-iterator/src/client/index.ts
  packages/durable-event-iterator/src/client/plugin.test.ts
  packages/durable-event-iterator/src/client/plugin.ts
  packages/durable-event-iterator/src/consts.ts
  packages/durable-event-iterator/src/durable-object/consts.ts
  packages/durable-event-iterator/src/durable-object/event-storage.test.ts
  packages/durable-event-iterator/src/durable-object/event-storage.ts
  packages/durable-event-iterator/src/durable-object/handler.test.ts
  packages/durable-event-iterator/src/durable-object/handler.ts
  packages/durable-event-iterator/src/durable-object/index.ts
  packages/durable-event-iterator/src/durable-object/object.test.ts
  packages/durable-event-iterator/src/durable-object/object.ts
  packages/durable-event-iterator/src/durable-object/upgrade.test.ts
  packages/durable-event-iterator/src/durable-object/upgrade.ts
  packages/durable-event-iterator/src/durable-object/websocket-manager.test.ts
  packages/durable-event-iterator/src/durable-object/websocket-manager.ts
  packages/durable-event-iterator/src/event-iterator.test-d.ts
  packages/durable-event-iterator/src/event-iterator.test.ts
  packages/durable-event-iterator/src/event-iterator.ts
  packages/durable-event-iterator/src/index.ts
  packages/durable-event-iterator/src/object.test-d.ts
  packages/durable-event-iterator/src/object.ts
  packages/durable-event-iterator/src/plugin.test.ts
  packages/durable-event-iterator/src/plugin.ts
  packages/durable-event-iterator/src/schemas.ts
  packages/durable-event-iterator/tests/shared.ts
  packages/durable-event-iterator/tsconfig.json
  packages/durable-event-iterator/tsconfig.test.json
  packages/shared/src/index.ts
  playgrounds/cloudflare-worker/package.json
  playgrounds/cloudflare-worker/src/components/chat-room.tsx
  playgrounds/cloudflare-worker/src/lib/chat-room.ts
  playgrounds/cloudflare-worker/src/lib/orpc.ts
  playgrounds/cloudflare-worker/worker-configuration.d.ts
  playgrounds/cloudflare-worker/worker/dos/chat-room.ts
  playgrounds/cloudflare-worker/worker/index.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: size:XXL

#682 feat(standard-server-peer)!: use string instead of number for unique ID
  packages/client/src/adapters/message-port/rpc-link.test.ts
  packages/client/src/adapters/websocket/rpc-link.test.ts
  packages/durable-event-iterator/src/durable-object/handler.test.ts
  packages/durable-event-iterator/src/durable-object/object.test.ts
  packages/durable-event-iterator/src/durable-object/websocket-manager.test.ts
  packages/durable-event-iterator/src/durable-object/websocket-manager.ts
  packages/server/src/adapters/bun-ws/rpc-handler.test.ts
  packages/server/src/adapters/crossws/rpc-handler.test.ts
  packages/server/src/adapters/message-port/rpc-handler.test.ts
  packages/server/src/adapters/websocket/rpc-handler.test.ts
  packages/server/src/adapters/ws/rpc-handler.test.ts
  packages/server/src/hibernation/event-iterator.test.ts
  packages/server/src/hibernation/event-iterator.ts
  packages/shared/src/id.test.ts
  packages/shared/src/id.ts
  packages/shared/src/iterator.ts
  packages/shared/src/queue.test.ts
  packages/shared/src/queue.ts
  packages/standard-server-peer/src/client.test.ts
  packages/standard-server-peer/src/client.ts
  packages/standard-server-peer/src/codec.test.ts
  packages/standard-server-peer/src/codec.ts
  packages/standard-server-peer/src/event-iterator.test.ts
  packages/standard-server-peer/src/event-iterator.ts
  packages/standard-server-peer/src/server.test.ts
  packages/standard-server-peer/src/server.ts
  packages/standard-server/src/hibernation.test.ts
  packages/standard-server/src/hibernation.ts
Labels: size:L

#687 feat(server): enhance call util to support signal and lastEventId options
  packages/server/src/procedure-utils.test-d.ts
  packages/server/src/procedure-utils.test.ts
  packages/server/src/procedure-utils.ts
Labels: size:S

#692 docs: custom body parser
  apps/content/.vitepress/config.ts
  apps/content/docs/advanced/extend-body-parser.md
  apps/content/docs/file-upload-download.md
Labels: size:M

#699 feat(trpc): trpc router to orpc router
  apps/content/.vitepress/config.ts
  apps/content/docs/openapi/integrations/trpc.md
  packages/trpc/.gitignore
  packages/trpc/README.md
  packages/trpc/package.json
  packages/trpc/src/index.ts
  packages/trpc/src/to-orpc-router.test-d.ts
  packages/trpc/src/to-orpc-router.test.ts
  packages/trpc/src/to-orpc-router.ts
  packages/trpc/tests/shared.ts
  packages/trpc/tsconfig.json
  pnpm-lock.yaml
Labels: size:XL

#704 docs: Building Custom Plugins
  apps/content/.vitepress/config.ts
  apps/content/docs/advanced/building-custom-plugins.md
Labels: size:L
